name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am IST
    # Runs every minute
    - cron: '* * * * *'
  push:
      branches:
        - master
      paths:
        - ".github/workflows/wakatime.yaml"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_SHORT_INFO: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_PROJECTS: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART: "False"
          SHOW_EDITORS: "False" 
          LOCALE: "en"
          SHOW_OS: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_COMMIT: "False"
          COMMIT_MESSAGE: "Updated with Wakatime Metrics"
          COMMIT_USERNAME: "wakatime-bot"
